AWSTemplateFormatVersion: 2010-09-09
Description: >-
  file-conversion-util
Transform:
  - AWS::Serverless-2016-10-31
Resources:
  # This is a Lambda function config associated with the source code: hello-from-lambda.js
  processFileUpload:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/file-conversion-lambda.processFileUpload
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: A lambda process S3 uploads and create resized files and store on S3
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
        - S3ReadPolicy:
            BucketName: thumbnail-creator-uploads
